### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by okdistribute** [local-first-web/relay#6]
Sometimes, I get this error in the relay server when doing production testing with fun edge cases, such as clearing data from a device and disconnecting from the relay unexpectedly. In a real app this would look like someone uninstalling the app/clear cache while their peer is actively sending websocket messages & trying to connect to them.

I don't think that the relay should ever throw an error and crash, is there a way to catch all of these errors and log them? Would a PR be welcome on this?

```
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
    at Server.sendIntroduction (/Users/okdistribute/dev/backchannel/node_modules/@localfirst/relay/dist/Server.js:95:74)
    at WebSocket.<anonymous> (/Users/okdistribute/dev/backchannel/node_modules/@localfirst/relay/dist/Server.js:74:34)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/Users/okdistribute/dev/backchannel/node_modules/express-ws/node_modules/ws/lib/receiver.js:69:10)
```

**Comment by HerbCaudill** [comment]
Hey, @okdistribute - absolutely the relay shouldn't crash because of a misbehaving client - a PR would definitely be welcome. 

I'm fine with wrapping everything in try/catch blocks and & logging errors for now, especially if you need to get a patch up quickly. In the slightly longer run, I'd like to understand better what sorts of things a client can do to cause an error on the server, reproduce those scenarios in tests, and handle them explicitly.

**Comment by ryanhlewis** [comment]
On Heroku, even without testing edge cases, the server crashes if the JSON sent is malformatted.
This is obviously a large security problem, as the server can be kept down just by sending bad requests to keep crashing it.

Here is a screenshot to clarify, and while I don't have a PR for you, I suppose the fix would be somewhere in simply rejecting malformatted JSON before the parse can crash the server.

https://ibb.co/9WTBJG5

Edit: Here is the PR.
https://github.com/local-first-web/relay/pull/8

As for the long run, it is obvious that JSON.parse() cannot parse what is not JSON being sent.
The explicit way to deal with this is using a large REGEX function to iterate through each and every message sent.
https://stackoverflow.com/questions/3710204/how-to-check-if-a-string-is-a-valid-json-string-in-javascript-without-using-try

All in all, it's probably best to leave the parse() error as an error and catch it, as checking each and every message for validity will consume far more overhead than is really necessary for this kind of bug.
